<?php if($this->usecss): ?>
<style>
    .clearfix:after {
        content: ".";
        display: block;
        clear: both;
        visibility: hidden;
        line-height: 0;
        height: 0;
    }

    .add {
        border-bottom:1px dotted #627D90;
        padding-bottom:10px;
        height: 10px;
    }

    .button_menu{
        height: 10px;
        padding-top: 10px;
    }
    .button_menu a.menu, .add a.menu, #paging a.menu{
        padding: 0 10px;
        background-color: #F57912;
        color: #FFF;
        margin-left: 5px;
    }

    .button_menu a.menu {float: right;}

    .add a.menu{float: left;}

    #paging{
        margin-top:20px;
        margin-bottom: 10px;
    }

    #paging a.page{
        border:1px solid #134B7C;
        color:black;width:20px;
        text-align:center;
        background-color:#D9DFE4;
        display:block;float:left;
        margin-right:3px;
        margin-bottom:3px;
        width: 30px;
        padding-top: 2px;
        padding-bottom: 2px;
    }

    #paging .clearer{
        height:10px;
        width:10px;
        float:left;
    }
    div.item img.events_logo{
        float: left;
        max-width: 170px;
        height: auto;
        padding-top: 10px;
        max-height: 110px;
    }
</style>
<?php endif; ?>
<script type="text/javascript">
    $(document).ready(function(){
        
        $('select#archiveYear').change(function(){
            document.location.href = $("#archiveYear").val();
        });

    });
</script>
<div id="paging">
    <div>
        <a class="menu" href="<?php echo lw_page::getInstance()->getUrl(array("cmd"=>"showList")); ?>">
        <?php if ($this->lang == "en"): ?>
            back to actual events
        <?php else: ?>
            zur&uuml;ck zu den aktuellen Eintr&auml;gen
        <?php endif; ?>
        </a>
    </div>
    <div>
        <select id="archiveYear">
            <?php foreach($this->availableYears as $year => $active): ?>
            <option value="<?php echo lw_page::getInstance()->getUrl(array("cmd"=>"showArchive", "year"=>$year)); ?>" <?php if($this->year == $year): ?> selected="selected"<?php endif; ?>><?php echo $year; ?>&nbsp;&nbsp;</option>
            <?php endforeach; ?>
        </select>
    </div>
</div>
<?php if ($this->collection->count() > 0) : ?>
    <?php foreach ($this->collection as $entry) : ?>
        <div class="item">
            <?php if ($this->admin) : ?>
                <div class="button_menu">
                    <a class="menu" href="<?php echo \lw_page::getInstance()->getUrl(array("cmd"=>"deleteEntry", "id" => $entry->getValueByKey('id'))); ?>" onclick="return confirm('Diesen Eintrag wirklich l&ouml;schen ?');">l&ouml;schen</a>
                    <a class="menu" href="<?php echo \lw_page::getInstance()->getUrl(array("cmd"=>"showEditEntryForm", "id" => $entry->getValueByKey('id'))); ?>">bearbeiten</a>
                </div>
            <?php endif; ?>
            <?php if ($entry->getValueByKey("opt1file")) : ?>
                <?php
                list($width) = getimagesize($this->config['path']['resource'].'lw_events'."/".$entry->getValueByKey("opt1file"));
                if ($width < 170) {
                    $div_width = 300 + (170 - $width);
                }
                else{
                    $div_width = 300;
                }
                ?>
                <div class="clearfix">
                    <img class="events_logo" src="<?php echo $this->config['url']['resource'].'lw_events/'.$entry->getValueByKey("opt1file"); ?>" >
                    <div style="float:left;width: <?php echo $div_width; ?>px;">
                        <div>
                            <?php
                            $date2 = "";
                            if ($this->entity->getValueByKey("opt4number") != $this->entity->getValueByKey("opt2number")) {
                                $date2 = ' - '.$this->formatDate($this->entity->getValueByKey('opt4number'));
                            }
                            echo $this->formatDate($this->entity->getValueByKey('opt2number')).$date2;
                            ?>
                        </div>

                        <h1 class="events_headline"><?php echo $entry->getValueByKey("opt1text"); ?></h1>
                        <h2 class="events_location"><?php echo $entry->getValueByKey("opt2text"); ?></h2>
                    </div>
                </div>
            <?php else: ?>
                <div>
                    <?php
                    $date2 = "";
                    if ($entry->getValueByKey("opt4number") != $entry->getValueByKey("opt2number")) {
                        $date2 = ' - '.$this->formatDate($entry->getValueByKey('opt4number'));
                    }
                    echo $this->formatDate($entry->getValueByKey('opt2number')).$date2;
                    ?>
                </div>

                <h1 class="events_headline"><?php echo $entry->getValueByKey("opt1text"); ?></h1>
                <h2 class="events_location"><?php echo $entry->getValueByKey("opt2text"); ?></h2>
            <?php endif; ?>

            <div>
                <p>
                    <?php
                        if ($this->lang == "en") {
                            $more = "more";
                        }
                        else {
                            $more = "mehr";
                        }
                    if ($entry->getValueByKey("opt5number") == 3) {
                        echo $entry->getValueByKey("opt2clob");
                        echo "...[<a class=\"extern\" target=\"_blank\" href=\"" . $entry->getValueByKey("opt3text") . "\">" . $more . "</a>]";
                    }

                    if ($entry->getValueByKey("opt5number") == 2) {
                        echo $entry->getValueByKey("opt2clob");
                        echo "...[<a class=\"intern\" target=\"_blank\" href=\"".lw_page::getInstance($entry->getValueByKey("opt1number"))->getUrl()."\">" . $more . "</a>]";
                    }

                    if ($entry->getValueByKey("opt5number") == 1) {
                        $str = "";
                        if (strlen($entry->getValueByKey("opt1clob")) > 250) {
                            $str = substr($entry->getValueByKey("opt1clob"), 0, 250);
                        }
                        else {
                            echo $entry->getValueByKey("opt1clob");
                        }
                        echo $str . "...[<a class=\"intern\" href=\"".lw_page::getInstance()->getUrl(array("cmd"=>"showDetail", "id"=>$entry->getValueByKey("id")))."\">" . $more . "</a>]";
                    }
                    ?></p>
            </div>
        </div>
    <?php endforeach; ?>
<?php else : ?>
    <div class="item">
        <div class="button_menu">
            <p>keine Eintr&auml;ge vorhanden</p>
        </div>
    </div>
<?php endif; ?>
<div id="paging">
    <a class="menu" href="<?php echo lw_page::getInstance()->getUrl(array("cmd"=>"showList")); ?>">
        <?php if ($this->lang == "en"): ?>
            back to actual events
        <?php else: ?>
            zur&uuml;ck zu den aktuellen Eintr&auml;gen
        <?php endif; ?>
    </a>
</div>