<?php 

function lwEventPrepareEntryTextAndMoreLink($entry)
{
    if ($entry->getValueByKey("opt5number") == 3) {
        $array['text'] = $entry->getValueByKey("opt2clob");
        $array['targeturl'] = $entry->getValueByKey("opt3text");
        $array['class'] = "extern";
    }

    if ($entry->getValueByKey("opt5number") == 2) {
        $array['text'] = $entry->getValueByKey("opt2clob");
        $array['targeturl'] = lw_page::getInstance($entry->getValueByKey("opt1number"))->getUrl();
        $array['class'] = "intern";
    }

    if ($entry->getValueByKey("opt5number") == 1) {
        if (strlen($entry->getValueByKey("opt1clob")) > 250) {
            $array['text'] = substr(strip_tags($entry->getValueByKey("opt1clob")), 0, 250).'...';
        }
        else {
            $array['text'] = $entry->getValueByKey("opt1clob");
        }
        $array['targeturl'] = lw_page::getInstance()->getUrl(array("cmd"=>"showDetail", "id"=>$entry->getValueByKey("id")));
        $array['class'] = "intern";
    }
    return $array;
}

function lwEventGetDateOutput($entry)
{
    $date2 = "";
    if ($entry->getValueByKey("opt4number") != $entry->getValueByKey("opt2number")) {
        $date2 = ' - '.lw_object::formatDate($entry->getValueByKey('opt4number'));
    }
    return lw_object::formatDate($entry->getValueByKey('opt2number')).$date2;
}

function lwEventGetImageWidth($config, $entry)
{
    list($width) = getimagesize($config['path']['resource'].'lw_events'."/".$entry->getValueByKey("opt1file"));
    if ($width < 170) {
        $div_width = 300 + (170 - $width);
    }
    else {
        $div_width = 300;
    }
    return $div_width;
}

?>
<?php if($this->usecss): ?>
<style>
    .clearfix:after {
        content: ".";
        display: block;
        clear: both;
        visibility: hidden;
        line-height: 0;
        height: 0;
    }

    .add {
        border-bottom:1px dotted #627D90;
        padding-bottom:10px;
        height: 10px;
    }

    .button_menu{
        height: 10px;
        padding-top: 10px;
    }
    .button_menu a.menu, .add a.menu, #paging a.menu{
        padding: 0 10px;
        background-color: #F57912;
        color: #FFF;
        margin-left: 5px;
    }

    .button_menu a.menu {float: right;}

    .add a.menu{float: left;}

    #paging{
        margin-top:20px;
        margin-bottom: 10px;
    }

    #paging a.page{
        border:1px solid #134B7C;
        color:black;width:20px;
        text-align:center;
        background-color:#D9DFE4;
        display:block;float:left;
        margin-right:3px;
        margin-bottom:3px;
        width: 30px;
        padding-top: 2px;
        padding-bottom: 2px;
    }

    #paging .clearer{
        height:10px;
        width:10px;
        float:left;
    }
    div.item img.events_logo{
        float: left;
        max-width: 170px;
        height: auto;
        padding-top: 10px;
        max-height: 110px;
    }
</style>
<?php endif; ?>
<div id="lwevents">

    <?php if($this->archiveView): ?>
    <script type="text/javascript">
        $(document).ready(function(){

            $('select#archiveYear').change(function(){
                document.location.href = $("#archiveYear").val();
            });

        });
    </script>
    <div id="paging">
        <div>
            <a href="<?php echo lw_page::getInstance()->getUrl(array("cmd"=>"showList")); ?>">
            <?php if ($this->lang == "en"): ?>back to actual events<?php else: ?>zur&uuml;ck zu den aktuellen Eintr&auml;gen<?php endif; ?>
            </a>
        </div>
        <div style="margin-left:10px; margin-top:10px;">
            <?php if ($this->lang == "en"): ?>Year<?php else: ?>Archivjahr<?php endif; ?>: <select id="archiveYear">
                <?php foreach($this->availableYears as $year => $active): ?>
                <option value="<?php echo lw_page::getInstance()->getUrl(array("cmd"=>"showArchive", "year"=>$year)); ?>" <?php if($this->year == $year): ?> selected="selected"<?php endif; ?>><?php echo $year; ?>&nbsp;&nbsp;</option>
                <?php endforeach; ?>
            </select>
        </div>
    </div>
<?php else: ?>
<?php if ($this->admin) : ?>
    <div class="add">
        <a class="menu" href="<?php echo $this->addUrl; ?>"><?php if ($this->lang == "en"): ?>add new event<?php else: ?>neuen Termin anlegen<?php endif; ?></a>
    </div>
<?php endif; ?>
<?php endif; ?>

<?php if ($this->collection->count() > 0) : ?>
    <?php foreach ($this->collection as $entry) : ?>
        <div class="item">
            <?php if ($this->admin) : ?>
                <div class="button_menu">
                    <a class="menu" href="<?php echo \lw_page::getInstance()->getUrl(array("cmd"=>"deleteEntry", "id" => $entry->getValueByKey('id'))); ?>" onclick="return confirm('Diesen Eintrag wirklich l&ouml;schen ?');"><?php if ($this->lang == "en"): ?>delete<?php else: ?>l&ouml;schen<?php endif; ?></a>
                    <a class="menu" href="<?php echo \lw_page::getInstance()->getUrl(array("cmd"=>"showEditEntryForm", "id" => $entry->getValueByKey('id'))); ?>"><?php if ($this->lang == "en"): ?>edit<?php else: ?>bearbeiten<?php endif; ?></a>
                </div>
            <?php endif; ?>
            <?php if ($entry->getValueByKey("opt1file")) : ?>
                <div class="clearfix">
                    <img class="events_logo" src="<?php echo $this->config['url']['resource'].'lw_events/'.$entry->getValueByKey("opt1file"); ?>" >
                    <div style="float:left;width: <?php echo lwEventGetImageWidth($this->config, $entry); ?>px;">
            <?php endif; ?>                        
                        <div class="events_date">
                            <?php  echo lwEventGetDateOutput($entry); ?>
                        </div>
                        <h1><?php echo $entry->getValueByKey("opt1text"); ?></h1>
                        <?php if(strlen($entry->getValueByKey("opt2text"))>0 && $entry->getValueByKey("opt2text") != "."): ?><h2><?php echo $entry->getValueByKey("opt2text"); ?></h2><?php endif; ?>
            <?php if ($entry->getValueByKey("opt1file")) : ?>
                    </div>
                </div>
            <?php endif; ?>

            <div>
                <p>
                    <?php 
                        $array = lwEventPrepareEntryTextAndMoreLink($entry); 
                        if(strlen($array['text'])>0): echo $array['text']; endif; ?>
                    <a class="<?php echo $array['class']; ?>" <?php if($array['class'] == "extern"): ?>target="_blank"<?php endif; ?> href="<?php echo $array['targeturl']; ?>">[<?php if ($this->lang == "en"): ?>more<?php else: ?>mehr<?php endif; ?>]</a>
                </p>
            </div>
        </div>
    <?php endforeach; ?>
    <?php else : ?>
        <div class="item">
            <div class="button_menu">
                <p><?php if ($this->lang == "en"): ?>no events available<?php else: ?>keine Eintr&auml;ge vorhanden<?php endif; ?></p>
            </div>
        </div>
    <?php endif; ?>

    <?php if(!$this->archiveView): ?>
    <div id="paging">
        <a href="<?php echo lw_page::getInstance()->getUrl(array("cmd"=>"showArchive")); ?>">
            <?php if ($this->lang == "en"): echo "go to archive"; else: echo "zum Archiv"; endif; ?>
        </a>
    </div>
    <?php endif; ?>
</div>