<style>
    .clearfix:after {
        content: ".";
        display: block;
        clear: both;
        visibility: hidden;
        line-height: 0;
        height: 0;
    }

    .add {
        border-bottom:1px dotted #627D90;
        padding-bottom:10px;
        height: 10px;
    }

    .button_menu{
        height: 10px;
        padding-top: 10px;
    }
    .button_menu a.menu, .add a.menu, #paging a.menu{
        padding: 0 10px;
        background-color: #F57912;
        color: #FFF;
        margin-left: 5px;
    }

    .button_menu a.menu {float: right;}

    .add a.menu{float: left;}

    #paging{
        margin-top:20px;
        margin-bottom: 10px;
    }

    #paging a.page{
        border:1px solid #134B7C;
        color:black;width:20px;
        text-align:center;
        background-color:#D9DFE4;
        display:block;float:left;
        margin-right:3px;
        margin-bottom:3px;
        width: 30px;
        padding-top: 2px;
        padding-bottom: 2px;
    }

    #paging .clearer{
        height:10px;
        width:10px;
        float:left;
    }
    div.item img.events_logo{
        float: left;
        max-width: 170px;
        height: auto;
        padding-top: 10px;
        max-height: 110px;
    }
</style>
<?php if ($this->admin) : ?>
    <div class="add">
        <a class="menu" href="<?php echo $this->addUrl; ?>">neuen Termin anlegen</a>
    </div>
<?php endif; ?>

<?php if ($this->collection->count() > 0) : ?>
    <?php foreach ($this->collection as $entry) : ?>
        <div class="item">
            <?php if ($this->admin) : ?>
                <div class="button_menu">
                    <a class="menu" href="<?php echo \lw_page::getInstance()->getUrl(array("cmd"=>"delete", "id" => $entry->getValueByKey('id'))); ?>" onclick="return confirm('Diesen Eintrag wirklich l&ouml;schen ?');">l&ouml;schen</a>
                    <a class="menu" href="<?php echo \lw_page::getInstance()->getUrl(array("cmd"=>"showEditEntryForm", "id" => $entry->getValueByKey('id'))); ?>">bearbeiten</a>
                </div>
            <?php endif; ?>
            <?php if ($entry->getValueByKey("opt1file")) : ?>
                <?php
                list($width) = getimagesize($this->config['path']['resource'].'lw_events'."/".$entry->getValueByKey("opt1file"));
                if ($width < 170) {
                    $div_width = 300 + (170 - $width);
                }
                else{
                    $div_width = 300;
                }
                ?>
                <div class="clearfix">
                    <img class="events_logo" src="<?php echo $this->config['url']['resource'].'lw_events/'.$entry->getValueByKey("opt1file"); ?>" >
                    <div style="float:left;width: <?php echo $div_width; ?>px;">
                        <div>
                            <?php
                            $year = substr($entry->getValueByKey('opt2number'), 0, 4);
                            $month = substr($entry->getValueByKey('opt2number'), 4, 2);
                            $day = substr($entry->getValueByKey('opt2number'), 6, 2);

                            $date2 = "";
                            if ($entry->getValueByKey("opt4number") != $entry->getValueByKey("opt2number")) {
                                $year2 = substr($entry->getValueByKey('opt4number'), 0, 4);
                                $month2 = substr($entry->getValueByKey('opt4number'), 4, 2);
                                $day2 = substr($entry->getValueByKey('opt4number'), 6, 2);

                                $date2 = ' - ' . $day2 . '.' . $month2 . '.' . $year2;
                            }
                            echo $day . '.' . $month . '.' . $year . $date2;
                            ?>
                        </div>

                        <h1><?php echo $entry->getValueByKey("opt1text"); ?></h1>

                        <h2><?php echo $entry->getValueByKey("opt2text"); ?></h2>
                    </div>
                </div>
            <?php else: ?>
                <div>
                    <?php
                    $year = substr($entry->getValueByKey('opt2number'), 0, 4);
                    $month = substr($entry->getValueByKey('opt2number'), 4, 2);
                    $day = substr($entry->getValueByKey('opt2number'), 6, 2);

                    $date2 = "";
                    if ($entry->getValueByKey("opt4number") != $entry->getValueByKey("opt2number")) {
                        $year2 = substr($entry->getValueByKey('opt4number'), 0, 4);
                        $month2 = substr($entry->getValueByKey('opt4number'), 4, 2);
                        $day2 = substr($entry->getValueByKey('opt4number'), 6, 2);

                        $date2 = ' - ' . $day2 . '.' . $month2 . '.' . $year2;
                    }
                    echo $day . '.' . $month . '.' . $year . $date2;
                    ?>
                </div>

                <h1><?php echo $entry->getValueByKey("opt1text"); ?></h1>

                <h2><?php echo $entry->getValueByKey("opt2text"); ?></h2>
            <?php endif; ?>

            <div>
                <p>
                    <?php
                    if ($entry->getValueByKey("opt5number" == 3)) {
                        if ($this->lang == "en") {
                            $more = "more";
                        }
                        else {
                            $more = "mehr";
                        }
                        echo $entry->getValueByKey("opt2clob");
                        echo "...[<a class=\"extern\" target=\"_blank\" href=\"" . $entry->getValueByKey("opt3text") . "\">" . $more . "</a>]";
                    }

                    if ($entry->getValueByKey("opt5number") == 2) {
                        if ($this->lang == "en") {
                            $more = "more";
                        }
                        else {
                            $more = "mehr";
                        }
                        echo $entry->getValueByKey("opt2clob");
                        echo "...[<a class=\"intern\" target=\"_blank\" href=\"".lw_page::getInstance($entry->getValueByKey("opt1number"))->getUrl()."\">" . $more . "</a>]";
                    }

                    if ($entry->getValueByKey("opt5number") == 1) {
                        $str = "";
                        if ($this->lang == "en") {
                            $more = "more";
                        }
                        else {
                            $more = "mehr";
                        }
                        if (strlen($entry->getValueByKey("opt1clob")) > 250) {
                            $str = substr($entry->getValueByKey("opt1clob"), 0, 250);
                        }
                        else {
                            echo $entry->getValueByKey("opt1clob");
                        }
                        echo $str . "...[<a class=\"intern\" href=\"".lw_page::getInstance()->getUrl(array("cmd"=>"showDetail", "id"=>$entry->getValueByKey("id")))."\">" . $more . "</a>]";
                    }
                    ?></p>
            </div>
        </div>
    <?php endforeach; ?>
<?php else : ?>
    <div class="item">
        <div class="button_menu">
            <p>keine Eintr&auml;ge vorhanden</p>
        </div>
    </div>
<?php endif; ?>
<div id="paging">
    <a class="menu" href="<?php echo $this->baseUrl . "&show=archive" ?>">
        <?php
        if ($this->lang == "en") {
            $gotToArchive = "go to archive";
        }
        else {
            $gotToArchive = "zum Archiv";
        }

        echo $gotToArchive;
        ?>
    </a>
</div>