<link rel="alternate" type="application/rss+xml" title="RSS" href="<?php echo \lw_page::getInstance()->getUrl(array("cmd"=>"rss"));?>">
<div id="LwEvents">

    <?php if($this->archiveView): ?>
    <script type="text/javascript">
        $(document).ready(function(){

            $('select#LwEvents_SelectArchiveYear').change(function(){
                document.location.href = $("#LwEvents_SelectArchiveYear").val();
            });

        });
    </script>
    
    <div id="LwEvents_ArchiveNavigation">

        <div class="LwEvents_BackToCurrentEvents">
            <a class="LwEvents_ButtonBackToCurrentEvents" href="<?php echo lw_page::getInstance()->getUrl(array("cmd"=>"showList")); ?>">
            <span><?php if ($this->lang == "en"): ?>back to current events<?php else: ?>zur&uuml;ck zu den aktuellen Eintr&auml;gen<?php endif; ?></span>
            </a>
        </div>

        <div class="LwEvents_SelectArchiveYear">
            <span class="LwEvents_SelectArchiveYear_Label"><?php if ($this->lang == "en"): ?>Year<?php else: ?>Archivjahr<?php endif; ?>: </span>
            <select id="LwEvents_SelectArchiveYear">
                <?php foreach($this->availableYears as $year => $active): ?>
                <option value="<?php echo lw_page::getInstance()->getUrl(array("cmd"=>"showArchive", "year"=>$year)); ?>" <?php if($this->year == $year): ?> selected="selected"<?php endif; ?>><?php echo $year; ?>&nbsp;&nbsp;</option>
                <?php endforeach; ?>
            </select>
        </div>
        
    </div>
    <?php else: ?>
        <div class="LwEvents_Admin">
        <?php if ($this->admin) : ?>
            <a class="LwEvents_AddButton" href="<?php echo $this->addUrl; ?>"><span><?php if ($this->lang == "en"): ?>add new event<?php else: ?>neuen Termin anlegen<?php endif; ?></span></a>
        <?php endif; ?>
        <?php if ($this->ical) : ?>
            <a class="LwEvents_AddButton ICalAll" href="<?php echo lw_page::getInstance()->getUrl(array("cmd"=>"downloadCompleteICals")); ?>"><span><?php if ($this->lang == "en"): echo "download all events"; else: echo "alle Termine herunterladen"; endif; ?></span></a>
        <?php endif; ?>
        </div>
    <?php endif; ?>

    <div id="LwEvents_MainList">

    <?php if ($this->collection->count() > 0) : ?>
        <?php foreach ($this->collection as $entry) : ?>
        <div class="LwEvents_EventEntry">
            <?php if ($this->admin) : ?>
            <div class="LwEvents_Admin">
                    <a class="LwEvents_DeleteButton" href="<?php echo \lw_page::getInstance()->getUrl(array("cmd"=>"deleteEntry", "id" => $entry->getValueByKey('id'))); ?>" onclick="return confirm('Diesen Eintrag wirklich l&ouml;schen ?');"><span><?php if ($this->lang == "en"): ?>delete<?php else: ?>l&ouml;schen<?php endif; ?></span></a>
                    <a class="LwEvents_EditButton" href="<?php echo \lw_page::getInstance()->getUrl(array("cmd"=>"showEditEntryForm", "id" => $entry->getValueByKey('id'))); ?>"><span><?php if ($this->lang == "en"): ?>edit<?php else: ?>bearbeiten<?php endif; ?></span></a>
            </div>
            <?php endif; ?>
            <?php if ($entry->getValueByKey("opt1file")) : ?>
            <div class="clearfix">
                <img class="LwEvents_Logo" src="<?php echo $this->config['url']['resource'].'lw_events/'.$entry->getValueByKey("opt1file"); ?>" >
                <div class="LwEvents_EntryWithLogo" style="float:left;width: <?php echo $this->PrepareLogoWidthHelper->execute($this->config, $entry); ?>px;">
            <?php endif; ?>                        
                    <h2 class="LwEvents_EntryTitle"><?php echo $entry->getValueByKey("opt1text"); ?></h2>
                    <div class="LwEvents_EntryDate">
                        <?php echo $this->PrepareEventDateOutputHelper->execute($entry); ?><?php if(strlen($entry->getValueByKey("opt2text"))>0 && $entry->getValueByKey("opt2text") != "."): ?><span class="LwEvents_EntryLocation">, <?php echo $entry->getValueByKey("opt2text"); ?></span><?php endif; ?>
                    </div>
            <?php if ($entry->getValueByKey("opt1file")) : ?>
                </div>
            </div>
            <?php endif; ?>

            <div class="LwEvents_EntryTeaserText">
                <?php  $array = $this->PrepareEntryTextAndMoreLinkHelper->execute($entry); 
                if(strlen($array['text'])>0): echo $array['text']; endif; ?><br>
                <a class="LwEvents_EntryDetailLink <?php echo $array['class']; ?>" <?php if($array['class'] == "extern"): ?>target="_blank"<?php endif; ?> href="<?php echo $array['targeturl']; ?>"><span>[<?php if ($this->lang == "en"): ?>more<?php else: ?>mehr<?php endif; ?>]</span></a>
                <?php if ($this->ical) : ?>
                <a class="LwEvents_EditButton ICalSingle" href="<?php echo \lw_page::getInstance()->getUrl(array("cmd"=>"downloadICal", "id" => $entry->getValueByKey('id'))); ?>"><span>[iCal <?php if ($this->lang == "en"): ?> download<?php else: ?>herunterladen<?php endif; ?>]</span></a>
                <?php endif; ?>
            </div>
            
        </div>
        <?php endforeach; ?>
        <?php else : ?>
        <div class="LwEvents_NoEntryAvailable">
            <?php if ($this->lang == "en"): ?>no events available<?php else: ?>keine Eintr&auml;ge vorhanden<?php endif; ?>
        </div>
        <?php endif; ?>

        <?php if(!$this->archiveView): ?>
        <div id="LwEvents_ArchiveNavigation">
            <a href="<?php echo lw_page::getInstance()->getUrl(array("cmd"=>"showArchive")); ?>">
                <span><?php if ($this->lang == "en"): echo "go to archive"; else: echo "zum Archiv"; endif; ?></span>
            </a>
        </div>
        <?php endif; ?>
    </diV>
</div>
