<div id="LwEvents">
    
    <div class="LwEvents_BackToEventsList">
        <a class="LwEvents_ButtonBackToEventsList" href="<?php echo $this->PrepareGetBackUrlFromDetailHelper->execute($this->entity); ?>">
        <span><?php if ($this->lang == "en"): ?>back<?php else: ?>zur&uuml;ck<?php endif; ?></span>
        </a>
    </div>

    <div class="LwEvents_EntryDetail">
    
        <?php if ($this->entity->getValueByKey("opt1file")) : ?>
        <div class="clearfix">
            <img class="LwEvents_Logo" src="<?php echo $this->config['url']['resource'].'lw_events/'.$this->entity->getValueByKey("opt1file"); ?>" >
            <div class="LwEvents_EntryWithLogo" style="float:left;width: <?php echo $this->PrepareLogoWidthHelper->execute($this->config, $this->entity); ?>px;">
        <?php endif; ?>                        
                <div class="LwEvents_EntryDate">
                    <?php echo $this->PrepareEventDateOutputHelper->execute($this->entity); ?>
                </div>
                <h2 class="LwEvents_EntryTitle"><?php echo $this->entity->getValueByKey("opt1text"); ?></h2>
                <?php if(strlen($this->entity->getValueByKey("opt2text"))>0): ?><div class="LwEvents_EntryLocation"><?php echo $this->entity->getValueByKey("opt2text"); ?></div><?php endif; ?>
        <?php if ($this->entity->getValueByKey("opt1file")) : ?>
            </div>
        </div>
        <?php endif; ?>

        <div class="LwEvents_EntryTeaserText">
            <?php echo $this->entity->getValueByKey("opt1clob"); ?>
        </div>
    </div>
    
</div>    
