<style>
    #containerCms, #containerMainText, #containerExt, #containerTeasertext{display: none;}
</style>
<script>
    $(document).ready(function() {
        var icon = "<?php echo $this->mediaUrl; ?>pics/fatcow_icons/16x16_0180/calendar.png";

        $("#datepicker_show").datepicker({
            altField: "#datepicker",
            altFormat: "yymmdd",
            showOn: "button",
            buttonImage: "<?php echo $this->mediaUrl ?>pics/fatcow_icons/16x16_0180/calendar.png",
            buttonImageOnly: true
        });
        $("#datepicker_show").datepicker("option", "dateFormat", "dd.mm.yy");

        var date = "<?php echo $this->formatDate($this->entity->getValueByKey('opt2number')); ?>";
        $("#datepicker_show").datepicker("setDate", date);

        $("#datepicker_show2").datepicker({
            altField: "#datepicker2",
            altFormat: "yymmdd",
            showOn: "button",
            buttonImage: "<?php echo $this->mediaUrl ?>pics/fatcow_icons/16x16_0180/calendar.png",
            buttonImageOnly: true
        });
        $("#datepicker_show2").datepicker("option", "dateFormat", "dd.mm.yy");

        var date2 = "<?php echo $this->formatDate($this->entity->getValueByKey('opt4number')); ?>";
        console.log('date2: '+date2);
        $("#datepicker_show2").datepicker("setDate", date2);

        <?php if ($this->entity->getValueByKey("opt5number") == 2) : ?>
        $('#containerTeasertext').show();
        $('#containerCms').show();
        <?php elseif ($this->entity->getValueByKey("opt5number") == 1) : ?>
        $('#containerMainText').show();
        <?php elseif ($this->entity->getValueByKey("opt5number") == 3) : ?>
        $('#containerTeasertext').show();
        $('#containerExt').show();
        <?php else : ?>
        $('#containerMainText').show();
        <?php endif; ?>
            
        $('#typetext').click(function(){
            $('#containerCms').hide();
            $('#containerExt').hide();
            $('#containerTeasertext').hide();
            $('#containerMainText').show();
        });
        $('#typecms').click(function(){
            $('#containerMainText').hide();
            $('#containerExt').hide();
            $('#containerTeasertext').show();
            $('#containerCms').show();
        });
        $('#typeext').click(function(){
            $('#containerMainText').hide();
            $('#containerCms').hide();
            $('#containerTeasertext').show();
            $('#containerExt').show();
        });            
            
    });

// Notice: The simple theme does not use all options some of them are limited to the advanced theme
    tinyMCE.init({
        mode: "specific_textareas",
        editor_selector: "mceEditor",
        theme: "advanced",
	    theme_advanced_buttons1 : "bold,italic,bullist,numlist,link,unlink,undo,redo,removeformat,code",
        language: "de",
        convert_urls: false,
        relative_urls: false,
        remove_script_host: false
    });
</script>
<div id="LwEvents">
    <div id="LwEvents_EntryForm">
        <h2><?php 
            if ($this->formtype =="new") {
                if ($this->lang == "en") {
                    echo "New Event";
                } 
                else {
                    echo "Neue Veranstaltung";
                }
            }
            else {
                if ($this->lang == "en") {
                    echo "Edit Event";
                } 
                else {
                    echo "Veranstaltung bearbeiten";
                }
            }
        ?></h2>
        
        <div class="LwEvents_BackToEventsList">
            <a class="LwEvents_ButtonBackToEventsList" href="<?php 
                if ($this->entity->getValueByKey("opt4number") < date("Ymd") && $this->entity->getValueByKey("opt4number")) {
                    echo \lw_page::getInstance()->getUrl(array("cmd"=>"showArchive", "year" => substr($this->entity->getValueByKey("opt2number"), 0, 4))); 
                }
                else {
                    echo \lw_page::getInstance()->getUrl(array("cmd"=>"showList")); 
                }
            ?>">
            <span><?php if ($this->lang == "en"): ?>back<?php else: ?>zur&uuml;ck<?php endif; ?></span>
            </a>
        </div>

        <?php if(is_array($this->errors)): ?>
        <div class="LwEvents_ErrorMesage"><?php if ($this->lang == "en"): ?>Errors occured!<?php else: ?>Es gibt Fehler!<?php endif; ?></div>
        <?php endif; ?>    

        <form action="<?php echo $this->actionUrl; ?>" method="POST" ENCTYPE="multipart/form-data">

            <!-- Datum von bis -->

            <div class="LwEventsForm_Block">
                
                <div class="LwEventsForm_Date LwEventsForm_DateFrom">
                    <label for="datepicker"><?php if ($this->lang == "en"): ?>Date:<span>(Start)</span><?php else: ?>Datum:<span>(von)</span><?php endif; ?></label><br>
                    <input id="datepicker_show" type="text" value="" disabled>
                    <input id="datepicker" type="hidden" name="opt2number" value="">
                </div>
                <?php echo $this->ValidationErrorViewHelper->getOutput($this->errors['opt2number']); ?>
                
                <div class="LwEventsForm_date LwEventsForm_DateTo">
                    <label for="datepicker"><?php if ($this->lang == "en"): ?>Date:<span>(End)</span><?php else: ?>Datum:<span>(bis)</span><?php endif; ?></label><br>
                    <input id="datepicker_show2" type="text" value="" disabled>
                    <input id="datepicker2" type="hidden" name="opt4number" value="">
                </div>
                <?php if(isset($this->errors["opt4number"]["ENDBEFORESTART"])): ?>
                    <div class="alert alert-block alert-error">
                        <h3 class="alert-heading"><?php if ($this->lang == "en"): ?>Error<?php else: ?>Fehler<?php endif; ?>:</h3>
                        <p><?php if ($this->lang == "en"): ?>The end of the event can not take place before the event has started.<?php else: ?>Das Enddatum darf nicht kleiner sein als das Startdatum.<?php endif; ?></p>
                    </div>
                <?php endif; ?>
                
            </div>

            <!-- Überschrift -->

            <div class="LwEventsForm LwEvents_Headline">
                <label for="headline1"><?php if ($this->lang == "en"): ?>Headline<?php else: ?>&Uuml;berschrift<?php endif; ?>:</label>
                <input id="headline1" type="text" name="opt1text" value="<?php echo $this->entity->getValueByKey("opt1text"); ?>">
                <?php echo $this->ValidationErrorViewHelper->getOutput($this->errors['opt1text']); ?>
            </div>

            <!-- Ort -->

            <div class="LwEventsForm LwEvents_Location">
                <label for="opt2text"><?php if ($this->lang == "en"): ?>Place<?php else: ?>Ort<?php endif; ?>:</label>
                <input id="opt2text" type="text" name="opt2text" value="<?php echo $this->entity->getValueByKey("opt2text"); ?>">
                <?php echo $this->ValidationErrorViewHelper->getOutput($this->errors['opt2text']); ?>
            </div>

            <!-- Logo -->

            <div class="LwEventsForm LwEvents_Logo">
                <div id="LwEventsForm_UploadedFile">
                    <div class="LwEvents_HelpText"><?php if ($this->lang == "en"): ?>Uploaded Logo File (only .gif, .jpg and .png allowed)<?php else: ?>Hochgeladene Logodatei (nur .gif, .jpg und .png erlaubt)<?php endif; ?></div>
                    <?php if($this->oldEntity->getValueByKey("opt1file")) :?>
                        <div class="LwEvents_Admin">
                            <a class="LwEvents_deleteLogoButton" href="<?php echo lw_page::getInstance()->getUrl(array("cmd"=>"deleteLogo", "id"=>$this->entity->getValueByKey("id"))); ?>" onclick="return confirm('<?php if ($this->lang == "en"): ?>Do you really want to delete the Logo?<?php else: ?>Logo wirklich l&ouml;schen ?<?php endif; ?>');" ><?php if ($this->lang == "en"): ?>delete Logo<?php else: ?>Logo l&ouml;schen<?php endif; ?></a>
                        </div>
                        <img class="LwEvents_LogoPreview" src="<?php echo $this->config['url']['resource']."lw_events/".$this->oldEntity->getValueByKey("opt1file"); ?>">
                    <?php endif; ?>
                </div>
                <input class="upload" name="opt1file" type="file">
                <?php echo $this->ValidationErrorViewHelper->getOutput($this->errors['opt1file']); ?>
            </div>

            <!-- Termintyp -->

            <div class="LwEventsForm LwEvents_Type">
                <div class="LwEvents_HelpText"><?php if ($this->lang == "en"): ?>Choose description type<?php else: ?>Bitte Termin-Eingabe w&auml;hlen<?php endif; ?>:</div>

                <div class="LwEventsForm_Block">
                    <input class="LwEventsForm LwEventsTextType" type="radio" id="typetext" value="1" name="opt5number" <?php if (!$this->entity->getValueByKey("opt5number") || $this->entity->getValueByKey("opt5number") == 1): ?> checked="checked" <?php endif; ?>>
                    <label class="LwEventsForm LwEventsTextType" for="typetext"><?php if ($this->lang == "en"): ?>free text<?php else: ?>Texteingabe<?php endif; ?></label><br/>
                </div>

                <div class="LwEventsForm_Block">
                    <input class="LwEventsForm LwEventsCMSType" type="radio" id="typecms" value="2" name="opt5number" <?php if ($this->entity->getValueByKey("opt5number") == 2) : ?> checked="checked" <?php endif; ?>>
                    <label class="LwEventsForm LwEventsCMSType" for="typecms"><?php if ($this->lang == "en"): ?>link to internal cms page<?php else: ?>Verweis auf eine CMS-Seite<?php endif; ?></label><br>
                </div>

                <div class="LwEventsForm_Block">
                    <input class="LwEventsForm LwEventsExternalType" type="radio" id="typeext" value="3" name="opt5number" <?php if ($this->entity->getValueByKey("opt5number") == 3) : ?> checked="checked" <?php endif; ?>>
                    <label class="LwEventsForm LwEventsExternalType" for="typeext"><?php if ($this->lang == "en"): ?>link to external page<?php else: ?>Verweis auf eine externe Seite<?php endif; ?></label>
                </div>
            </div>

            <!-- Text -->

            <div id="containerMainText" class="LwEventsForm LwEvents_MainText">
                <label for="mainText">Text:</label><br>
                <textarea style="width:495px; height:250px;" id="mainText" class="text mceEditor beliebig" name="opt1clob"><?php echo $this->entity->getValueByKey("opt1clob"); ?></textarea>
                <?php echo $this->ValidationErrorViewHelper->getOutput($this->errors['opt1clob']); ?>
            </div>

            <!-- Teasertext -->

            <div id="containerTeasertext" class="LwEventsForm LwEvents_TeaserText">
                <label for="teasertext">Teasertext:</label><br>
                <textarea style="width:495px; height:250px;" id="teasertext" class="text mceEditor beliebig" name="opt2clob"><?php echo $this->entity->getValueByKey("opt2clob"); ?></textarea>
                <?php echo $this->ValidationErrorViewHelper->getOutput($this->errors['opt2clob']); ?>
            </div>
            
            
            <!-- Seitenindex -->

            <div id="containerCms" class="LwEventsForm LwEvents_PageIndex">
                <label for="link"><?php if ($this->lang == "en"): ?>Page Id<?php else: ?>Seiten Id<?php endif; ?>:</label><br>
                <span class="LwEvents_HelpText"><?php if ($this->lang == "en"): ?>enter internal CMS page ID number<?php else: ?>Soll auf eine Seite im CMS verwiesen werden, so ist hier die Indexnr. einzutragen.<?php endif; ?></span><br>
                <input id="cmslink" class="mceEditor" type="text" name="opt1number" value="<?php echo $this->entity->getValueByKey("opt1number"); ?>" >
                <?php echo $this->ValidationErrorViewHelper->getOutput($this->errors['opt1number']); ?>
            </div>

            <!-- Target URL -->

            <div id="containerExt" class="LwEventsForm LwEvents_TargetUrl">
                <label for="link">Url:</label><br>
                <input id="extlink" type="text" name="opt3text" value="<?php echo $this->entity->getValueByKey("opt3text"); ?>" >
                <?php echo $this->ValidationErrorViewHelper->getOutput($this->errors['opt3text']); ?>
            </div>

            <!-- Submit Button -->

            <div id="formButtons" class="LwEventsForm LwEvents_SubmitButton">
                <input type="submit" value="<?php if ($this->lang == "en"): ?>save<?php else: ?>speichern<?php endif; ?>">
            </div>

        </form>

    </div>
</div>    
