<?php 
if ($this->calendar) {
    echo $this->CalendarOutputHelper->execute($this->configuration, $this->collection);
}

if ($this->collection->count()>0) : 
    foreach ($this->collection as $entry):
        $nextdate = $this->formatDate($entry->getValueByKey('opt2number'));
        break;
    endforeach;
?>
    <div id="LwEvents_nextEvent">
        <span>
            <?php if ($this->lang == "en"): ?>next event: <?php else : ?>n&auml;chster Termin: <?php endif; echo $nextdate; ?>
        </span>
    </div>

    <div id="LwEvents_TeaserList">
        <?php 
        $i=0;    
        foreach ($this->collection as $entry) : 
            $i++;
            ?>
        <div class="LwEvents_EventEntry">
            <div class="LwEvents_EventDate"><?php echo $this->PrepareEventDateOutputHelper->execute($entry) ?></div>
            <?php if(strlen($entry->getValueByKey('opt2text'))>0 && $entry->getValueByKey('opt2text') != "."): ?>
            <div class="LwEvents_EventLocation">
                <?php echo $entry->getValueByKey('opt2text'); ?>
            </div>
            <?php endif; ?>
            <h2 class="LwEvents_EventTitle"><?php echo $entry->getValueByKey('opt1text'); ?></h2>
            <?php
            if ($entry->getValueByKey("opt5number") == 3) {
                $targetUrl = $entry->getValueByKey("opt3text");
                $class = "extern";
            }
            if ($entry->getValueByKey("opt5number") == 2) {
                $targetUrl = lw_page::getInstance($entry->getValueByKey("opt1number"))->getUrl();
                $class = "intern";
            }
            if ($entry->getValueByKey("opt5number") == 1) {
                $targetUrl = lw_page::getInstance()->getUrl(array("cmd"=>"showDetail", "id"=>$entry->getValueByKey("id")));
                $class = "intern";
            }
            ?>
            <a class="LwEvents_EntryDetailLink <?php echo $class; ?>" <?php if($class=="extern"): ?>target="_blank" <?php endif; ?>href="<?php echo $targetUrl; ?>"><span>[<?php if ($this->lang == "en"): ?>more<?php else: ?>mehr<?php endif; ?>]</span></a>
        </div>
            <?php 
            if ($i == $this->teaserelements): break; endif; 
        endforeach; 
        ?>
    </div>
<?php endif; ?>
