<?php 
if ($this->calendar) {
?>
<?php if($this->usecss): ?>
<style>
    #veranstaltungsteaser .veranstaltung{
        border-top:1px solid #a2b2bf;
        padding:6px 16px;
    }
    #veranstaltungsteaser .lightblue{color:#627D90;}

    #veranstaltungen{position: relative;}

    #veranstaltungen #infobox{
        position: absolute;
        top: -1px;
        left: -205px;
        min-height: 230px;
        width: 200px;
        background-color: #F7F7F7;
        border: 2px solid #a2b2bf;
        border-radius: 10px;
        color: #666;
        padding-top: 5px;
        display: none;

    }

    #veranstaltungen #infobox #date{
        padding-left: 10px;
        margin: 20px 0 5px 0;
    }

    #veranstaltungen #infobox #close{
        cursor: pointer;
        padding-left: 5px;
    }

    #veranstaltungen #infobox .calelement{
        border-top: 1px solid #a2b2bf;
        padding: 15px 0;
    }
    #veranstaltungen #infobox .calelement h2{margin: 0;}

    #veranstaltungen #infobox .calelement h1, #veranstaltungen #infobox .calelement h2{padding: 0 10px;}

    #hiddenCalElement{display: none;}


    .close {
        color: #000000;
        float: right;
        font-size: 20px;
        font-weight: bold;
        line-height: 20px;
        text-shadow: 0 1px 0 #FFFFFF;
        font-family: Verdana,Helvetica,Arial,sans-serif;
        padding-right: 10px;
        -ms-filter: "progid:DXImageTransform.Microsoft.Alpha(Opacity=20)";
        filter: alpha(opacity=20);
        -moz-opacity: 0.2;
        -khtml-opacity: 0.2;
        opacity: 0.2;
    }
    .close:hover{
        -ms-filter: "progid:DXImageTransform.Microsoft.Alpha(Opacity=100)";
        filter: alpha(opacity=100);
        -moz-opacity: 1;
        -khtml-opacity: 1;
        opacity: 1;
    }
</style>
<?php endif; ?>  
<?php
    echo $this->CalendarOutputHelper->execute($this->configuration, $this->collection);
}

if ($this->collection->count()>0) : 
    foreach ($this->collection as $entry):
        $nextdate = $this->formatDate($entry->getValueByKey('opt2number'));
        break;
    endforeach;
?>
    <div id="LwEvents_nextEvent">
        <span>
            <?php if ($this->lang == "en"): ?>next event: <?php else : ?>n&auml;chster Termin: <?php endif; echo $nextdate; ?>
        </span>
    </div>

    <div id="LwEvents_TeaserList">
        <?php 
        $i=0;    
        foreach ($this->collection as $entry) : 
            $i++;
            ?>
        <div class="LwEvents_EventEntry">
            <div class="LwEvents_EventDate"><?php echo $this->PrepareEventDateOutputHelper->execute($entry) ?></div>
            <?php if(strlen($entry->getValueByKey('opt2text'))>0 && $entry->getValueByKey('opt2text') != "."): ?>
            <div class="LwEvents_EventLocation">
                <?php echo $entry->getValueByKey('opt2text'); ?>
            </div>
            <?php endif; ?>
            <h2 class="LwEvents_EventTitle"><?php echo $entry->getValueByKey('opt1text'); ?></h2>
            <?php
            if ($entry->getValueByKey("opt5number") == 3) {
                $targetUrl = $entry->getValueByKey("opt3text");
                $class = "extern";
            }
            if ($entry->getValueByKey("opt5number") == 2) {
                $targetUrl = lw_page::getInstance($entry->getValueByKey("opt1number"))->getUrl();
                $class = "intern";
            }
            if ($entry->getValueByKey("opt5number") == 1) {
                $targetUrl = lw_page::getInstance()->getUrl(array("cmd"=>"showDetail", "id"=>$entry->getValueByKey("id")));
                $class = "intern";
            }
            ?>
            <a class="LwEvents_EntryDetailLink <?php echo $class; ?>" <?php if($class=="extern"): ?>target="_blank" <?php endif; ?>href="<?php echo $targetUrl; ?>"><span>[<?php if ($this->lang == "en"): ?>more<?php else: ?>mehr<?php endif; ?>]</span></a>
        </div>
            <?php 
            if ($i == $this->teaserelements): break; endif; 
        endforeach; 
        ?>
    </div>
<?php endif; ?>
